
CREATE TABLE [dbo].[SPB_BACEN_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_BMFBMC_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_BMFBMD_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_CBLC_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_CENTRAL_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_CETIP_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_CIP_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_BACEN] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_BMFBMC] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_BMFBMD] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_CBLC] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_CENTRAL] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_CETIP] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_CIP] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_SELIC] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_LOG_IFBANCO_TECBAN] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_BACEN] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_BMFBMC] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_BMFBMD] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_CBLC] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_CENTRAL] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_CETIP] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_CIP] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_SELIC] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_IFBANCO_TO_TECBAN] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_DESTINO] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME_PUT] [datetime] NULL ,
	[MQ_MSG_ID_COA] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COA] [datetime] NULL ,
	[MQ_MSG_ID_COD] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_COD] [datetime] NULL ,
	[MQ_MSG_ID_REP] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MQ_DATETIME_REP] [datetime] NULL ,
	[MQ_HEADER] [binary] (512) NULL ,
	[SECURITY_HEADER] [binary] (332) NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[MSG_SEQ_APP] [int] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_SELIC_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPB_TECBAN_TO_IFBANCO] (
	[MSG_SEQ] [int] IDENTITY (1, 1) NOT NULL ,
	[MQ_MSG_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_CORREL_ID] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[DB_DATETIME] [datetime] NOT NULL ,
	[STATUS_MSG] [int] NOT NULL ,
	[MSG_ERRO_PROC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PROC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_QN_ORIGEM] [char] (48) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MQ_DATETIME] [datetime] NOT NULL ,
	[MQ_HEADER] [binary] (512) NOT NULL ,
	[SECURITY_HEADER] [binary] (332) NOT NULL ,
	[NU_OPE] [char] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[COD_MSG] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL ,
	[MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[NUM_CTRL_SIMM] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AI NULL ,
	[FLAG_PILOTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_BACEN] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_BACEN ] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_BMFBMC] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_BMFBMC] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_BMFBMD] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_BMFBMD] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_CBLC] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_CBLC] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_CENTRAL] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_CENTRAL] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_CETIP] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_CETIP] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_CIP] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_CIP] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_SELIC] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_SELIC] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_LOG_IFBANCO_TECBAN] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_LOG_IFBANCO_TECBAN] PRIMARY KEY  CLUSTERED 
	(
		[DB_DATETIME],
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_BACEN_TO_IFBANCO] ON [dbo].[SPB_BACEN_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_BMFBMC_TO_IFBANCO] ON [dbo].[SPB_BMFBMC_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_BMFBMD_TO_IFBANCO] ON [dbo].[SPB_BMFBMD_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_CBLC_TO_IFBANCO] ON [dbo].[SPB_CBLC_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_CENTRAL_TO_IFBANCO] ON [dbo].[SPB_CENTRAL_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_CETIP_TO_IFBANCO] ON [dbo].[SPB_CETIP_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_CIP_TO_IFBANCO] ON [dbo].[SPB_CIP_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_BACEN] ON [dbo].[SPB_IFBANCO_TO_BACEN]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_BMFBMC] ON [dbo].[SPB_IFBANCO_TO_BMFBMC]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_BMFBMD] ON [dbo].[SPB_IFBANCO_TO_BMFBMD]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_CBLC] ON [dbo].[SPB_IFBANCO_TO_CBLC]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_CENTRAL] ON [dbo].[SPB_IFBANCO_TO_CENTRAL]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_CETIP] ON [dbo].[SPB_IFBANCO_TO_CETIP]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_CIP] ON [dbo].[SPB_IFBANCO_TO_CIP]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_SELIC] ON [dbo].[SPB_IFBANCO_TO_SELIC]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_IFBANCO_TO_TECBAN] ON [dbo].[SPB_IFBANCO_TO_TECBAN]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_SELIC_TO_IFBANCO                                         ] ON [dbo].[SPB_SELIC_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

 CREATE  CLUSTERED  INDEX [IX_SPB_TECBAN_TO_IFBANCO] ON [dbo].[SPB_TECBAN_TO_IFBANCO]([DB_DATETIME], [MSG_SEQ]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SPB_BACEN_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_BACEN_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_BMFBMC_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_BMFBMC_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_BMFBMD_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_BMFBMD_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_CBLC_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_CBLC_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_CENTRAL_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_CENTRAL_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_CETIP_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_CETIP_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_CIP_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_CIP_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_BACEN] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_BACEN] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_BMFBMC] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_BMFBMC] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_BMFBMD] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_BMFBMD] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_CBLC] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_CBLC] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_CENTRAL] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_CENTRAL] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_CETIP] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_CETIP] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_CIP] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_CIP] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_SELIC] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_SELIC] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_IFBANCO_TO_TECBAN] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_IFBANCO_TO_TECBAN] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_SELIC_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_SELIC_TO_IFBANCO                                         ] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPB_TECBAN_TO_IFBANCO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPB_TECBAN_TO_IFBANCO] PRIMARY KEY  NONCLUSTERED 
	(
		[MSG_SEQ]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [IX1_SPB_BACEN_TO_IFBANCO] ON [dbo].[SPB_BACEN_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_BMFBMC_TO_IFBANCO] ON [dbo].[SPB_BMFBMC_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_BMFBMD_TO_IFBANCO] ON [dbo].[SPB_BMFBMD_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_CBLC_TO_IFBANCO] ON [dbo].[SPB_CBLC_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_CENTRAL_TO_IFBANCO] ON [dbo].[SPB_CENTRAL_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_CETIP_TO_IFBANCO] ON [dbo].[SPB_CETIP_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_CIP_TO_IFBANCO] ON [dbo].[SPB_CIP_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_BACEN ] ON [dbo].[SPB_LOG_IFBANCO_BACEN]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_BMFBMC] ON [dbo].[SPB_LOG_IFBANCO_BMFBMC]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_BMFBMD] ON [dbo].[SPB_LOG_IFBANCO_BMFBMD]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_CBLC] ON [dbo].[SPB_LOG_IFBANCO_CBLC]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_CENTRAL] ON [dbo].[SPB_LOG_IFBANCO_CENTRAL]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_CETIP] ON [dbo].[SPB_LOG_IFBANCO_CETIP]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_CIP] ON [dbo].[SPB_LOG_IFBANCO_CIP]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_SELIC] ON [dbo].[SPB_LOG_IFBANCO_SELIC]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_LOG_IFBANCO_TECBAN] ON [dbo].[SPB_LOG_IFBANCO_TECBAN]([FLAG_PROC], [DB_DATETIME]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_BACEN] ON [dbo].[SPB_IFBANCO_TO_BACEN]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_BACEN] ON [dbo].[SPB_IFBANCO_TO_BACEN]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_BMFBMC] ON [dbo].[SPB_IFBANCO_TO_BMFBMC]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_BMFBMC] ON [dbo].[SPB_IFBANCO_TO_BMFBMC]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_BMFBMD] ON [dbo].[SPB_IFBANCO_TO_BMFBMD]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_BMFBMD] ON [dbo].[SPB_IFBANCO_TO_BMFBMD]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_CBLC] ON [dbo].[SPB_IFBANCO_TO_CBLC]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_CBLC] ON [dbo].[SPB_IFBANCO_TO_CBLC]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_CENTRAL] ON [dbo].[SPB_IFBANCO_TO_CENTRAL]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_CENTRAL] ON [dbo].[SPB_IFBANCO_TO_CENTRAL]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_CETIP] ON [dbo].[SPB_IFBANCO_TO_CETIP]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_CETIP] ON [dbo].[SPB_IFBANCO_TO_CETIP]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_CIP] ON [dbo].[SPB_IFBANCO_TO_CIP]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_CIP] ON [dbo].[SPB_IFBANCO_TO_CIP]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_SELIC] ON [dbo].[SPB_IFBANCO_TO_SELIC]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_SELIC] ON [dbo].[SPB_IFBANCO_TO_SELIC]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_IFBANCO_TO_TECBAN] ON [dbo].[SPB_IFBANCO_TO_TECBAN]([MQ_MSG_ID]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX2_SPB_IFBANCO_TO_TECBAN] ON [dbo].[SPB_IFBANCO_TO_TECBAN]([MQ_QN_DESTINO], [FLAG_PROC]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_SELIC_TO_IFBANCO                                         ] ON [dbo].[SPB_SELIC_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

 CREATE  INDEX [IX1_SPB_TECBAN_TO_IFBANCO] ON [dbo].[SPB_TECBAN_TO_IFBANCO]([FLAG_PROC], [MQ_QN_ORIGEM]) WITH  FILLFACTOR = 50,  PAD_INDEX  ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO





CREATE TRIGGER [TRIGGER_SPB_BACEN_TO_IFBANCO] ON SPB_BACEN_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 





GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_BMFBMC_TO_IFBANCO] ON SPB_BMFBMC_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_BMFBMD_TO_IFBANCO] ON SPB_BMFBMD_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_CBLC_TO_IFBANCO] ON SPB_CBLC_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_CENTRAL_TO_IFBANCO] ON SPB_CENTRAL_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_CETIP_TO_IFBANCO] ON SPB_CETIP_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_CIP_TO_IFBANCO] ON SPB_CIP_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_BACEN ] ON SPB_LOG_IFBANCO_BACEN 
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_BACEN_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_BMFBMC] ON SPB_LOG_IFBANCO_BMFBMC
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_BMFBMC_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_BMFBMD] ON SPB_LOG_IFBANCO_BMFBMD
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_BMFBMD_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_CBLC] ON SPB_LOG_IFBANCO_CBLC
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_CBLC_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_CENTRAL] ON SPB_LOG_IFBANCO_CENTRAL
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_CENTRAL_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_CETIP] ON SPB_LOG_IFBANCO_CETIP
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_CETIP_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_CIP] ON SPB_LOG_IFBANCO_CIP
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_CIP_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_SELIC] ON SPB_LOG_IFBANCO_SELIC
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_SELIC_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_LOG_IFBANCO_TECBAN] ON SPB_LOG_IFBANCO_TECBAN
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @FlagProc char (1), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'CONSUMIDOR_COACOD'
select @FlagProc = i.FLAG_PROC from inserted i
set @sAppParm = 'SPB_LOG_IFBANCO_TECBAN_' + @FlagProc
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_BACEN] ON SPB_IFBANCO_TO_BACEN
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_BACEN'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_BACEN] ON SPB_IFBANCO_TO_BACEN
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_BMFBMC] ON SPB_IFBANCO_TO_BMFBMC
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_BMFBMC'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_BMFBMC] ON SPB_IFBANCO_TO_BMFBMC
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_BMFBMD] ON SPB_IFBANCO_TO_BMFBMD
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_BMFBMD'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_BMFBMD] ON SPB_IFBANCO_TO_BMFBMD
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_CBLC] ON SPB_IFBANCO_TO_CBLC
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_CBLC'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_CBLC] ON SPB_IFBANCO_TO_CBLC
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_CENTRAL] ON SPB_IFBANCO_TO_CENTRAL
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_CENTRAL'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_CENTRAL] ON SPB_IFBANCO_TO_CENTRAL
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_CETIP] ON SPB_IFBANCO_TO_CETIP
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_CETIP'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_CETIP] ON SPB_IFBANCO_TO_CETIP
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_CIP] ON SPB_IFBANCO_TO_CIP
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_CIP'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_CIP] ON SPB_IFBANCO_TO_CIP
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_SELIC] ON SPB_IFBANCO_TO_SELIC
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_SELIC'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_SELIC] ON SPB_IFBANCO_TO_SELIC
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER1_SPB_IFBANCO_TO_TECBAN] ON SPB_IFBANCO_TO_TECBAN
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_IFBANCO_TO_TECBAN'
select @sAppParm = i.MQ_QN_DESTINO from inserted i 
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER2_SPB_IFBANCO_TO_TECBAN] ON SPB_IFBANCO_TO_TECBAN
FOR UPDATE AS 
declare @Status_fluxo int , @Msg_seq_app int 
SELECT @Status_fluxo = i.STATUS_MSG from inserted i 
SELECT @Msg_seq_app = i.MSG_SEQ_APP from inserted i 
IF (@Status_fluxo = 31) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.MQ_MSG_ID = inserted.MQ_MSG_ID, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ = inserted.MQ_DATETIME_PUT 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 
IF (@Status_fluxo = 32) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG, 
       APP_MSG_PROCESSADAS.DATA_HORA_MQ_TRANS = inserted.MQ_DATETIME_COA 
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 31 
END 
IF (@Status_fluxo = 33) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO = inserted.STATUS_MSG  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
    AND   APP_MSG_PROCESSADAS.STATUS_FLUXO = 32 
END IF (@Status_fluxo >= 34) 
BEGIN
    UPDATE APP_MSG_PROCESSADAS 
       SET STATUS_FLUXO  = inserted.STATUS_MSG ,        MSG_ERRO_PROC = inserted.MSG_ERRO_PROC  
    FROM inserted 
    WHERE APP_MSG_PROCESSADAS.MSG_SEQ = @Msg_seq_app 
END 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_SELIC_TO_IFBANCO] ON SPB_SELIC_TO_IFBANCO                                         
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE TRIGGER [TRIGGER_SPB_TECBAN_TO_IFBANCO] ON SPB_TECBAN_TO_IFBANCO
FOR INSERT AS 
declare @sDBName varchar(15), @sTableName varchar(64), @sAppParm varchar(64), @result int, @Origem varchar(8), @Destino varchar(8) 
set @sDBName = 'SPBBD000'
set @sTableName = 'SPB_TABRECEBE'
select @Origem = SUBSTRING(i.MQ_QN_ORIGEM,8,8) from inserted i 
select @Destino = SUBSTRING(i.MQ_QN_ORIGEM,17,8) from inserted i 
set @sAppParm = 'CONSUMIDOR_RECEBE_SPB_' + @Origem + '_' + @Destino
exec @result = master..xp_PostEcb_Service @sDBName, @sTableName, @sAppParm 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

