version: '3.8'
services:
  db:
    container_name: SPBAdmin-postgresql
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: catalog
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './postgresql/data:/var/lib/postgresql/data'
volumes:
  db:
    driver: local
